# Generated by Django 4.0.1 on 2024-09-17 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalTransaction',
            fields=[
                ('payment_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('payer_id', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('merchant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('hash', models.CharField(max_length=64)),
                ('ChessCoin_SKU', models.CharField(default='N/A', max_length=255)),
                ('Nush_ChessCoin', models.BinaryField(null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'PayPal Transaction',
                'verbose_name_plural': 'PayPal Transactions',
            },
        ),
    ]
