# Generated by Django 5.1 on 2024-09-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayPal_ChessCoin', '0002_paypaltransaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paypaltransaction',
            name='user',
        ),
        migrations.AddField(
            model_name='paypaltransaction',
            name='identification_number',
            field=models.CharField(default='N/A', max_length=20, verbose_name='Identification Number'),
        ),
    ]
