# Generated by Django 4.0.1 on 2024-05-07 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationTokenTime',
            fields=[
                ('token_auth', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_session', models.BooleanField(default=True)),
                ('ip_address', models.CharField(max_length=45)),
            ],
        ),
    ]
