# Generated by Django 4.0.1 on 2024-05-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationtokentime',
            name='token_auth',
            field=models.CharField(max_length=512, primary_key=True, serialize=False),
        ),
    ]
