# Generated by Django 4.0.1 on 2024-05-04 05:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessLobbies',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('white_player', models.CharField(max_length=100)),
                ('black_player', models.CharField(blank=True, max_length=100, null=True)),
                ('game_status', models.CharField(default='pending', max_length=20)),
                ('game_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white_player', models.CharField(max_length=100)),
                ('black_player', models.CharField(max_length=100)),
                ('game_status', models.CharField(default='pending', max_length=20)),
                ('move_history', models.JSONField(default=list)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=10, null=True)),
                ('config', models.JSONField(blank=True)),
                ('ChessLobbies_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MultiplayerOnline.chesslobbies')),
            ],
        ),
    ]
