# Generated by Django 4.0.1 on 2024-05-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiplayerOnline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chesslobbies',
            name='black_player',
            field=models.CharField(default='', max_length=100),
        ),
    ]
