# Generated by Django 5.1 on 2024-09-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiplayerOnline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chesslobbies',
            name='amount',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
