# Generated by Django 4.0.1 on 2024-09-01 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MultiplayerOnline', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChessGame',
        ),
    ]
