# Generated by Django 5.1 on 2024-09-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiplayerOnline', '0002_chesslobbies_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chesslobbies',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
