# Generated by Django 4.0.1 on 2024-09-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiplayerOnline', '0002_delete_chessgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='chesslobbies',
            name='bet_amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='chesslobbies',
            name='winning_player',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chesslobbies',
            name='black_player',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
