# Generated by Django 4.0.1 on 2024-09-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiplayerOnline', '0003_chesslobbies_bet_amount_chesslobbies_winning_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chesslobbies',
            name='timer',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
