# Generated by Django 5.1 on 2024-09-20 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MultiplayerOnline', '0003_alter_chesslobbies_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chesslobbies',
            name='nush_bet',
        ),
    ]
