# Generated by Django 5.1 on 2024-09-30 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MultiplayerOnline', '0004_remove_chesslobbies_nush_bet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chesslobbies',
            name='Nush_ChessCoin_bet',
        ),
    ]
