# Generated by Django 4.0.1 on 2024-09-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiplayerOnline', '0004_chesslobbies_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chesslobbies',
            name='black_player',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='chesslobbies',
            name='white_player',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
