# Generated by Django 5.1 on 2024-11-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiplayerOnline', '0005_remove_chesslobbies_nush_chesscoin_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='chesslobbies',
            name='lobby_wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
