# Generated by Django 4.0.1 on 2024-09-08 03:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MultiplayerOnline', '0005_alter_chesslobbies_black_player_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BR', 'Bronce'), ('PL', 'Plata'), ('OR', 'Oro'), ('DI', 'Diamante'), ('MA', 'Maestro'), ('GM', 'Gran Maestro')], default='BR', max_length=2)),
            ],
        ),
        migrations.RenameField(
            model_name='chesslobbies',
            old_name='timer',
            new_name='timer_black_player',
        ),
        migrations.AddField(
            model_name='chesslobbies',
            name='timer_white_player',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.CreateModel(
            name='PlayerRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MultiplayerOnline.division')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo_rating', models.FloatField(default=1200, validators=[django.core.validators.MinValueValidator(0)])),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('1-0', 'White Wins'), ('0-1', 'Black Wins'), ('0.5-0.5', 'Draw')], max_length=10)),
                ('player_black', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_black', to='MultiplayerOnline.player')),
                ('player_white', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_white', to='MultiplayerOnline.player')),
            ],
        ),
    ]
