# Generated by Django 5.1 on 2024-09-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessCoin_Transaccions',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('white_player', models.CharField(blank=True, max_length=100)),
                ('black_player', models.CharField(blank=True, max_length=100)),
                ('game_status', models.CharField(default='None', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('this_chessboard', models.JSONField(default=dict)),
                ('winning_player', models.CharField(blank=True, default='N/A', max_length=100, null=True)),
                ('timer_black_player', models.PositiveIntegerField(default=10)),
                ('timer_white_player', models.PositiveIntegerField(default=10)),
                ('timer', models.PositiveIntegerField(default=10)),
                ('Nush_ChessCoin_bet', models.BinaryField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaccion_status', models.BooleanField(default=False)),
                ('fee_match', models.JSONField(default=dict)),
                ('validation_message', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
