# Generated by Django 4.0.1 on 2024-09-01 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('bank_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Type')),
                ('swift_code', models.CharField(blank=True, max_length=11, null=True, verbose_name='SWIFT Code')),
                ('account_number', models.CharField(blank=True, max_length=34, null=True, verbose_name='Account Number')),
                ('bank_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Address')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Additional Information')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
