# Generated by Django 5.1 on 2024-09-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessCoin', '0002_chesscoin_transaccions_fee_match_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chesscoin_transaccions',
            name='fee_match_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
