# Generated by Django 5.1 on 2024-09-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessCoin', '0004_chesscoin_transaccions_nush_amount_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chesscoin_transaccions',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
