# Generated by Django 5.1 on 2024-09-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessCoin', '0005_alter_chesscoin_transaccions_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chesscoin_transaccions',
            name='ended_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
