# Generated by Django 5.1 on 2024-10-12 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChessCoin', '0006_chesscoin_transaccions_ended_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chesscoin_transaccions',
            name='Nush_ChessCoin_bet',
        ),
        migrations.RemoveField(
            model_name='chesscoin_transaccions',
            name='fee_match',
        ),
        migrations.RemoveField(
            model_name='chesscoin_transaccions',
            name='nush_amount_verify',
        ),
    ]
