# Generated by Django 5.1 on 2024-10-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessCoin', '0007_remove_chesscoin_transaccions_nush_chesscoin_bet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chesscoin_transaccions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='chesscoin_transaccions',
            name='ended_at',
            field=models.DateTimeField(null=True),
        ),
    ]
